### ISSUE TITLE
Improve left menu style

### ISSUE THREAD

**Issue by gzoritchak** [data2viz/play.data2viz.io#8]
![image](https://user-images.githubusercontent.com/1110254/48095103-24d59300-e214-11e8-8612-83c760bda7c8.png)

**Comment by gzoritchak** [comment]
Don't use blue color on menu. It collides with the practice to have blue to indicate links. Here the blue indicates the current page and, because we have the mouse (non visible on capture) over it is has a underline. It is really disturbing.

Remove the blue color in the menu. Remove the underline for the active page.

**Comment by azertypow** [comment]
Current section in black, other section in light gray, link in blue on hover

![image](https://user-images.githubusercontent.com/12177073/48133636-c3ef9e80-e297-11e8-92cf-40200728429b.png)
