### ISSUE TITLE
Align CodeMirror to idea style

### ISSUE THREAD

**Issue by gzoritchak** [data2viz/play.data2viz.io#9]
A lot of people developing with kotlin are using Intellij Idea IDE. We should align code mirror theme to IDEA's one. 

![image](https://user-images.githubusercontent.com/1110254/48095515-4125ff80-e215-11e8-949a-a77c16154520.png)

**Comment by AlexanderPrendota** [comment]
Recently I created [`idea`](https://github.com/codemirror/CodeMirror/blob/master/theme/idea.css) & [`darcula`](https://github.com/codemirror/CodeMirror/blob/master/theme/darcula.css) themes in CodeMirror. I guess this issue about improving styles?

**Comment by gzoritchak** [comment]
No, it's because I looked at the documentation and didn't see the idea theme in the least. It was probably to late...

Thanks for the info.

**Comment by azertypow** [comment]
```
val d2vAttributes = mapOf(
    "theme" to "idea",
    ...
)
```
before:
![image](https://user-images.githubusercontent.com/12177073/48141654-9c0a3600-e2ab-11e8-80de-27bdd4932e48.png)

after:
![image](https://user-images.githubusercontent.com/12177073/48141536-6402f300-e2ab-11e8-9e3a-273b7bfd6466.png)

**Comment by AlexanderPrendota** [comment]
Hmm..may be I'll set the 'idea' theme as default 🤔
